### ISSUE TITLE
MemoryError: Unable to allocate 168. GiB for an array with shape (76821, 542, 542) and data type float64

### ISSUE THREAD

**Issue by Al-Dailami** [CRIPAC-DIG/TextING#17]
loading training set
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 76821/76821 [02:21<00:00, 543.88it/s]
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    train_adj, train_mask = preprocess_adj(train_adj)
  File "~/TextING/utils.py", line 153, in preprocess_adj
    return np.array(list(adj)), mask # coo_to_tuple(sparse.COO(np.array(list(adj)))), mask

**Comment by Al-Dailami** [comment]
Hello

Can you help me fix this problem!!!

**Comment by Magicat128** [comment]
Hi @Al-Dailami 

Which dataset are you using? You may try processing training samples in batches and concatenate them with NumPy.

**Comment by Al-Dailami** [comment]
Thanks a lot for your reply.

I'm working in a dataset that contains around 500,000 record of short texts. Can you please help me on how to modify the code to be able to process the data in batches.

Thanks a lot in advance for your valuable help.

**Comment by Al-Dailami** [comment]
Hello,
Now i have this ERROR!!

Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train_feature = preprocess_features(train_feature)
  File ".../TextING/utils.py", line 125, in preprocess_features
    feature = np.pad(feature, ((0,pad),(0,0)), mode='constant')
  File "<__array_function__ internals>", line 6, in pad
  File ".../lib/python3.7/site-packages/numpy/lib/arraypad.py", line 748, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File ".../lib/python3.7/site-packages/numpy/lib/arraypad.py", line 523, in _as_pairs
    return np.broadcast_to(x, (ndim, 2)).tolist()
  File "<__array_function__ internals>", line 6, in broadcast_to
  File ".../lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File ".../lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (1,2)

**Comment by Al-Dailami** [comment]
Hello,
I have modified the trainer to process data batch by batch..
Is this a right way?
https://github.com/CRIPAC-DIG/TextING/blob/c2492c276a6b59ca88337e582dfd2f3616f3988d/train.py#L124


b_train_adj, b_train_mask = preprocess_adj(train_adj[idx])
b_train_feature = preprocess_features(train_feature[idx])
feed_dict = construct_feed_dict(b_train_feature, b_train_adj, b_train_mask, train_y[idx], placeholders)
feed_dict.update({placeholders['dropout']: FLAGS.dropout})

**Comment by Magicat128** [comment]
> Hello,
> I have modified the trainer to process data batch by batch..
> Is this a right way?
> https://github.com/CRIPAC-DIG/TextING/blob/c2492c276a6b59ca88337e582dfd2f3616f3988d/train.py#L124
> 
> b_train_adj, b_train_mask = preprocess_adj(train_adj[idx])
> b_train_feature = preprocess_features(train_feature[idx])
> feed_dict = construct_feed_dict(b_train_feature, b_train_adj, train_mask, train_y[idx], placeholders)
> feed_dict.update({placeholders['dropout']: FLAGS.dropout})

@Al-Dailami 
Yes, you can do it. And it's your b_train_mask in feed_dict rather than train_mask :)

**Comment by bp20200202** [comment]
> Hello,
> I have modified the trainer to process data batch by batch..
> Is this a right way?
> https://github.com/CRIPAC-DIG/TextING/blob/c2492c276a6b59ca88337e582dfd2f3616f3988d/train.py#L124
> 
> b_train_adj, b_train_mask = preprocess_adj(train_adj[idx])
> b_train_feature = preprocess_features(train_feature[idx])
> feed_dict = construct_feed_dict(b_train_feature, b_train_adj, b_train_mask, train_y[idx], placeholders)
> feed_dict.update({placeholders['dropout']: FLAGS.dropout})

Hello, I would like to ask if I am still reporting memoryerror after changing the code given by you, have you ever experienced this situation?
